name: silkroad_online
description: A Silkroad Online inspired MMORPG game
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.1.0
  flame: ^1.29.0
  flutter_joystick: ^0.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/characters/
    - assets/images/monsters/
    - assets/images/maps/
    - assets/images/items/
    - assets/images/ui/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/maps/
