name: devilf
description: "A Flutter 2D MMORPG Game inspired by Al-Fath: Path of Revenge"
version: 0.1.0
homepage: https://github.com/ym6745476/devilf

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add support for internationalization
    sdk: flutter
  intl: ^0.18.0 # For internationalization
  web_socket_channel: ^2.4.0  # For real-time communication
  provider: ^6.0.5  # For state management
  shared_preferences: ^2.2.0  # For local storage
  path_provider: ^2.1.0  # For file system access
  yaml: ^3.1.2  # For configuration files
  flame: ^1.8.0  # For 2D game engine
  flame_audio: ^2.0.5  # For game audio
  flutter_joystick: ^0.0.3  # For virtual joystick control
  http: ^1.1.0  # For HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  assets:
    - assets/audio/
    - assets/images/
    - assets/game_data/
    - assets/config/
    - assets/i18n/ # Add internationalization assets

  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/GameFont-Regular.ttf
    - family: NotoKufiArabic # Add Arabic font
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700
